version: "3.9"

services:
  frontend:
    image: node:latest
    container_name: frontend
    working_dir: /usr/src/app
    volumes:
      - ./licenseplates-fe:/usr/src/app
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm start"
    environment:
      - NODE_ENV=development

  backend:
    # TODO: create image
    image: tiangolo/uvicorn-gunicorn-fastapi:python3.11
    container_name: backend
    working_dir: /usr/src/app
    volumes:
      - ./licenseplates:/usr/src/app/licenseplates
      - ./api.py:/usr/src/app/api.py
      - ./requirements.txt:/usr/src/app/requirements.txt
      - ./finetuned-model.pt:/usr/src/app/finetuned-model.pt
    command: sh -c "apt-get update && apt-get install -y python3-opencv && pip install -r requirements.txt && uvicorn api:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
